EVALUATE
CALCULATETABLE(
  SUMMARIZECOLUMNS(
    'dim_L1L2'[L1_Num],
    'dim_L1L2'[L1_Title],
    "Z_Algo",         [Z|Algo],
    "Z_Human",        [Z|Human],
    "RF_Count",       [RF#],
    "Question_Count", COUNTROWS('Questions')
  ),
  'Lkup_Key'[Key3] = "{KEY3}",
  'Questions'[IsActive] = 1,
  'Questions'[IsScored] = 1
)
ORDER BY 'dim_L1L2'[L1_Num]
